"use client";

import Link from "next/link";
import { LanguageSwitcher } from "@/components/language-switcher";
import { useI18n } from "@/components/locale-provider";
import { guideCopy } from "@/lib/guide-copy";

export default function GuidePage() {
  const { locale } = useI18n();
  const copy = guideCopy[locale];
  const homeHref = locale === "en" ? "/en" : "/";
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 selection:bg-indigo-500 selection:text-white">
      <header className="sticky top-0 z-50 border-b border-indigo-950/40 bg-slate-950/85 px-5 py-4 backdrop-blur-md">
        <div className="mx-auto flex max-w-4xl items-center justify-between gap-4">
          <Link href={homeHref} className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-tr from-indigo-500 to-purple-600">🔒</span><span><span className="block text-sm font-bold text-indigo-200">Chamber Protocol</span><span className="block text-[9px] font-mono text-slate-500">{copy.title}</span></span></Link>
          <div className="flex items-center gap-3"><LanguageSwitcher compact routeAware /><Link href={homeHref} className="text-xs font-semibold text-slate-400 hover:text-indigo-300">{copy.backHome}</Link></div>
        </div>
      </header>
      <main className="mx-auto max-w-4xl px-5 py-12 sm:py-16">
        <section className="mb-12 max-w-2xl"><div className="mb-4 inline-flex rounded-full border border-amber-800/50 bg-amber-950/30 px-3 py-1 text-[10px] font-semibold text-amber-300">{copy.badge}</div><h1 className="mb-4 text-3xl font-extrabold text-white sm:text-4xl">{copy.hero}</h1><p className="text-sm leading-7 text-slate-400">{copy.intro}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href="/echo/releases/chamber-extension-v0.5.8.zip" download className="rounded-xl bg-emerald-600 px-5 py-3 text-center text-sm font-bold text-white">{copy.download}</a><a href="#mapping" className="rounded-xl border border-slate-800 bg-slate-900 px-5 py-3 text-center text-sm font-semibold text-slate-300">{copy.mappingJump}</a></div></section>
        <section id="install" className="scroll-mt-24 border-t border-slate-900 pt-10"><h2 className="mb-2 text-xl font-bold">{copy.installTitle}</h2><p className="text-xs leading-6 text-slate-500">{copy.installIntro}</p><div className="my-5 rounded-xl border border-emerald-800/50 bg-emerald-950/20 p-4 text-xs leading-6 text-emerald-100"><strong>{copy.developerNoteTitle}</strong>{copy.developerNote}</div><div className="grid gap-4 sm:grid-cols-2">{copy.installSteps.map((step,index)=><article key={step.title} className="rounded-2xl border border-slate-850 bg-slate-900/50 p-5"><div className="mb-3 font-mono text-xs font-bold text-indigo-400">STEP {index+1}</div><h3 className="mb-2 text-sm font-bold">{step.title}</h3><p className="text-xs leading-6 text-slate-400">{step.body}</p></article>)}</div><div className="mt-5 rounded-xl border border-indigo-900/50 bg-indigo-950/20 p-4 text-xs leading-6 text-indigo-200">{copy.chromeNoteBefore} <code className="rounded bg-slate-950 px-1.5 py-1 font-mono text-indigo-300">chrome://extensions/</code> {copy.chromeNoteAfter}</div></section>
        <section id="mapping" className="mt-14 scroll-mt-24 border-t border-slate-900 pt-10"><h2 className="mb-2 text-xl font-bold">{copy.mappingTitle}</h2><p className="text-sm leading-7 text-slate-400">{copy.mappingIntro}</p><div className="mt-7 space-y-4">{copy.mappingSteps.map((item,index)=><article key={item.title} className="flex gap-4 rounded-2xl border border-slate-850 bg-slate-900/45 p-5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-purple-600 text-xs font-bold">{index+1}</span><div><h3 className="mb-1.5 text-sm font-bold">{item.title}</h3><p className="text-xs leading-6 text-slate-400">{item.body}</p></div></article>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-emerald-900/50 bg-emerald-950/15 p-4"><h3 className="mb-2 text-xs font-bold text-emerald-200">{copy.mappingCheckTitle}</h3><ul className="list-disc space-y-1.5 pl-5 text-xs text-slate-400">{copy.mappingChecks.map(item=><li key={item}>{item}</li>)}</ul></div><div className="rounded-xl border border-amber-900/50 bg-amber-950/15 p-4"><h3 className="mb-2 text-xs font-bold text-amber-200">{copy.wrongAccountTitle}</h3><p className="text-xs leading-6 text-slate-400">{copy.wrongAccount}</p></div></div><div className="mt-5 rounded-xl border border-rose-900/50 bg-rose-950/15 p-4 text-xs leading-6 text-rose-100">{copy.mappingImportant}</div></section>
        <NumberedSection title={copy.backupTitle} items={copy.backupSteps} />
        <TextSection title={copy.declarationTitle} body={copy.declarationBody} />
        <section className="mt-14 grid gap-6 border-t border-slate-900 pt-10 md:grid-cols-2"><InfoCard title={copy.echoTitle} body={copy.echoBody} tone="emerald"/><InfoCard title={copy.recoveryTitle} body={copy.recoveryBody} tone="rose"/></section>
        <section className="mt-14 border-t border-slate-900 pt-10"><h2 className="mb-2 text-xl font-bold">{copy.portabilityTitle}</h2><p className="text-sm leading-7 text-slate-400">{copy.portabilityBodyBefore} <code className="rounded bg-slate-900 px-1.5 py-1 font-mono text-indigo-300">https://devnet.irys.xyz/&lt;TX_ID&gt;</code> {copy.portabilityBodyAfter}</p><div className="mt-4 rounded-xl border border-amber-900/50 bg-amber-950/15 p-4 text-xs leading-6 text-amber-100">{copy.portabilityWarning}</div><p className="mt-4 text-xs text-slate-500">{copy.portabilityDev}</p></section>
        <section className="mt-14 border-t border-slate-900 pt-10"><h2 className="mb-2 text-xl font-bold">{copy.sharingTitle}</h2><p className="mb-6 text-sm leading-7 text-slate-400">{copy.sharingIntro}</p><ol className="grid gap-3 sm:grid-cols-2">{copy.sharingSteps.map((item,index)=><li key={item} className="rounded-xl border border-slate-850 bg-slate-900/40 p-4 text-xs leading-6 text-slate-300">{index+1}. {item}</li>)}</ol><div className="mt-4 rounded-xl border border-amber-900/50 bg-amber-950/15 p-4 text-xs leading-6 text-amber-100">{copy.sharingWarning}</div></section>
        <TextSection title={copy.updateTitle} body={copy.updateBody} />
        <section className="mt-14 border-t border-slate-900 pt-10"><h2 className="mb-7 text-xl font-bold">{copy.faqTitle}</h2><div className="space-y-3">{copy.faq.map(item=><details key={item.title} className="rounded-xl border border-slate-850 bg-slate-900/40 p-4"><summary className="cursor-pointer text-sm font-semibold"><span className="mr-2 text-indigo-400">＋</span>{item.title}</summary><p className="mt-3 border-t border-slate-800 pt-3 text-xs leading-6 text-slate-400">{item.body}</p></details>)}</div></section>
        <section className="mt-14 rounded-2xl border border-amber-900/40 bg-amber-950/10 p-6"><h2 className="mb-3 text-base font-bold text-amber-200">{copy.limitsTitle}</h2><ul className="list-disc space-y-2 pl-5 text-xs leading-6 text-slate-400">{copy.limits.map(item=><li key={item}>{item}</li>)}</ul></section>
      </main>
      <footer className="border-t border-indigo-950/20 py-8 text-center text-[10px] font-mono text-slate-600">© 2026 Chamber Protocol · <Link href={homeHref} className="text-indigo-500">{copy.footerBack}</Link></footer>
    </div>
  );
}

function NumberedSection({title,items}:{title:string;items:string[]}) { return <section className="mt-14 border-t border-slate-900 pt-10"><h2 className="mb-7 text-xl font-bold">{title}</h2><ol className="space-y-4">{items.map((item,index)=><li key={item} className="flex gap-4 rounded-2xl border border-slate-900 bg-slate-900/25 p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-indigo-600 text-xs font-bold">{index+1}</span><p className="text-sm leading-6 text-slate-300">{item}</p></li>)}</ol></section>; }
function TextSection({title,body}:{title:string;body:string}) { return <section className="mt-14 border-t border-slate-900 pt-10"><h2 className="mb-2 text-xl font-bold">{title}</h2><p className="text-sm leading-7 text-slate-400">{body}</p></section>; }
function InfoCard({title,body,tone}:{title:string;body:string;tone:"emerald"|"rose"}) { return <div className={`rounded-2xl border p-6 ${tone === "emerald" ? "border-emerald-900/40 bg-emerald-950/10" : "border-rose-900/40 bg-rose-950/10"}`}><h2 className={`mb-3 text-base font-bold ${tone === "emerald" ? "text-emerald-200" : "text-rose-200"}`}>{title}</h2><p className="text-xs leading-6 text-slate-400">{body}</p></div>; }
