import type { Locale } from "./i18n";

const zhTW = {
  extensionMissing: "未偵測到 Chamber Extension", sharingKeyMissing: "Chamber Extension 尚未建立分享金鑰",
  systemPasskeyTimeout: "系統 Passkey 操作已取消或逾時", extensionNoResponse: "Chamber Extension 沒有回應，請確認已安裝並重新載入", recoveryFailed: "Extension 復原操作失敗",
  passwordManagerTimeout: "密碼管理器在 60 秒內沒有完成 Passkey。若出現空白視窗，可改選 Windows Hello／Chrome。", // pragma: allowlist secret
  recoveryPendingC: "Passkey 與 Vault B 已建立。請保存下方 C，再按確認完成設定。", recoveryComplete: "✅ 復原設定已完成。Passkey 私鑰由所選提供者保管，不會交給 Chamber；離線復原碼 C 不會再次顯示。",
  recoveryStatusFailed: "無法讀取復原狀態：{error}", creatingShares: "正在由 Extension 建立 A、B、C 三份復原資料...", passkeySetupFailed: "無法建立 Passkey 設定",
  waitingSystemPasskey: "等待你在 Windows Hello 或 Chrome 中確認建立系統 Passkey（最多 60 秒）...", waitingManagerPasskey: "等待你在密碼管理器中確認建立 Passkey（最多 60 秒）...", passkeyVerifyFailed: "Passkey 驗證失敗",
  setupSaveC: "✅ A 已留在 Extension、B 已進入 Recovery Vault。請把 C 保存到另一個安全位置，再按確認。", setupFailed: "設定失敗：{error}", setupConfirmed: "✅ 2-of-3 金鑰復原設定完成。A 在 Extension、B 在 Vault、C 由您離線保存。", confirmFailed: "確認失敗：{error}",
  rotateConfirm: "將建立新的 A／B／C 復原組，並以新的 B 取代 Vault 內的舊 B。完成後，舊 C 將無法再搭配 Vault 還原。確定繼續？", rotateChecking: "正在驗證現有 Passkey，準備輪替復原組...", rotateUnavailable: "目前沒有可輪替的完整復原設定", passkeyReadFailed: "無法讀取 Passkey 設定", vaultRotateFailed: "Vault 份額 B 輪替失敗", rotateSaveC: "✅ Vault B 已輪替。請立即保存下方新的 C 並確認；舊 C 已失效。", rotateFailed: "輪替失敗：{error}",
  repairChecking: "正在確認本機 A 與 Passkey Vault B...", repairUnavailable: "本機沒有可用的 A 或尚未連結 Recovery Vault", repairSuccess: "✅ 已使用本機 A＋Passkey Vault B 完成金鑰修復。", repairFailed: "A＋B 修復失敗：{error}", pasteC: "請先貼上緊急復原碼 C。", checkingLocalC: "正在檢查本機 A 是否能與 C 直接還原...", localCSuccess: "✅ 已使用本機 A＋緊急復原碼 C 完成還原，不需要讀取 Vault。", invalidC: "緊急復原碼 C 格式不正確", incompleteC: "緊急復原碼 C 內容不完整", authenticateForB: "請使用原本建立的 Passkey 驗證，以取回 Vault 份額 B...", restoreSuccess: "✅ 金鑰已還原並完成輪替。請保存下方新的 C；舊的 C 已失效。", restoreFailed: "還原失敗：{error}",
  connectingMetaMask: "正在連結 MetaMask...", walletConnected: "錢包連結成功！", connectFailed: "連結失敗：{error}", startingSandbox: "啟動安全模擬錢包...", sandboxConnected: "模擬錢包連結成功！", disconnecting: "已斷開錢包連結。正在返回首頁...",
  decryptTimeout: "Chamber Extension 解密逾時", ownerDecryptFailed: "Owner 解密失敗", legacyOwnerOnly: "這是舊版私密備份，目前只有擁有者可解密；作者需建立新版修訂後才能分享。", installExtension: "請先安裝並連結 Chamber Extension。", noGrant: "尚未取得作者閱讀授權。", grantReadFailed: "無法讀取文章授權。", mediaDownloadFailed: "媒體下載失敗（{status}）", partialMedia: "文章已解密；{success}/{total} 張圖片成功，{failed} 張失敗。", decryptFailed: "解密失敗：{error}",
  decryptPostsPartial: "已解密 {success} 篇，{failed} 篇文字解密失敗。", decryptAlbums: "已解密 {posts} 篇；相簿圖片成功 {success}/{total} 張。", decryptAll: "已解密目前時光牆的 {count} 篇備份。",
  grantTimeout: "Chamber Extension 建立授權逾時", grantCreateFailed: "無法建立閱讀授權", requestFailed: "申請失敗", approvedUnlocking: "作者已允許閱讀，正在重新解鎖。", requestSent: "閱讀申請已送出，等待作者同意。", readingRequestFailed: "閱讀申請失敗", postNotVisible: "請先回到包含這篇文章的 Echo 時光牆再核准。", legacyReshare: "這是舊版文章，請先從 Facebook 重新備份成新版後再分享。", requestUpdateFailed: "無法更新閱讀申請", accessApproved: "已允許對方閱讀這一篇；對方不會取得你的復原金鑰。", accessRejected: "已拒絕閱讀申請。", requestHandleFailed: "無法處理閱讀申請",
  allFeed: "✨ 全部流", chamberDisconnected: "Chamber 未連結", readingRequests: "🔔 閱讀申請", guide: "使用指南",
  externalWallet: "外部錢包 {wallet}（不決定文章擁有權）", keyRecoverySettings: "🛡️ 金鑰復原設定", identityCopied: "Chamber 身分地址已複製！", copyWallet: "📋 複製錢包地址", disconnectExternalWallet: "👋 斷開外部錢包",
  recoveryTitle: "2-of-3 金鑰復原", recoveryIntro: "A 留在目前 Chrome 的 Chamber Extension；B 加密保存於 Recovery Vault；C 由您離線保存。任兩份可還原，Echo 只提供操作畫面，不保存完整金鑰。",
  recoveryReadyTitle: "復原設定已完成", recoveryReadyBody: "Extension A 與 Passkey 保護的 Vault B 已就緒；請繼續妥善保存你先前取得的 C。此處不保存或再次顯示 C。", rotateCSummary: "C 遺失或疑似外洩？產生新的 C", rotateProviderLabel: "輪替使用的 Passkey 提供者", passwordManager: "🔐 密碼管理器", systemPasskey: "🖥️ 系統 Passkey", rotateWarning: "需驗證現有 Passkey。系統會輪替 A、Vault B 與 C；完成後舊 C 立即失效。", rotateCButton: "產生新的 C 並使舊 C 失效",
  recoverySetupTitle: "建立復原設定並產生 C", recoverySetupBody: "Passkey 私鑰由 Bitwarden、Google Password Manager 或系統安全區保管，Chamber 不會取得或顯示它。完成後，Extension 保存 A、Vault 保存 B，並只顯示一次由你離線保存的 C。", passkeyProviderLabel: "Passkey 提供者", passwordManagerExamples: "Bitwarden／1Password 等", systemPasskeyExamples: "Windows Hello／Chrome", providerHint: "建立與日後復原請選擇同一個提供者。若密碼管理器出現白窗，改用系統 Passkey。", processing: "處理中...", saveCFirst: "請先保存下方復原碼 C", setupRecoveryButton: "建立復原設定並產生 C", // pragma: allowlist secret
  restoreToolSummary: "遺失 Extension 或更換裝置？開啟還原工具", restoreToolBody: "只有已經建立過復原設定，且手上持有 C 時才使用這裡。同裝置可由 A+C 還原；Extension 遺失後，先通過原 Passkey 取回 B，再以 B+C 還原。", restoreProviderLabel: "還原使用的 Passkey 提供者", pasteSavedC: "貼上你先前保存的緊急復原碼 C", restoreBC: "以 B＋C 還原並建立新復原組", repairAB: "本機 A 尚在：使用 Passkey Vault B 修復",
  emergencyCTitle: "緊急復原碼 C", emergencyCBody: "請保存到密碼管理器、手機安全區或紙本，不要只留在目前電腦。", cCopied: "復原碼 C 已複製；請貼到另一個安全位置後按完成。", copyC: "📋 複製 C", cSavedElsewhere: "我已將 C 保存到其他地方",
  identityUnavailableTitle: "尚未讀到這台 Chrome 的 Chamber 身分", identityUnavailableBody: "鏈上備份仍在；請確認 Extension 已啟用，再重新載入此頁即可解鎖。MetaMask 地址不代表文章擁有者。", wrongIdentity: "目前登入的是 {identity}，不是這個 Echo 時光牆的 Chamber 身分，因此私密文章不會自動解鎖。",
  requestsTitle: "閱讀申請", requestsBody: "核准操作在 Echo 完成，文章金鑰只由本機 Chamber Extension 處理。", noRequests: "目前沒有閱讀申請。", requestPost: "文章 {post} · {date}", approvePost: "允許這一篇", reject: "拒絕", approvedSingle: "✅ 已允許單篇閱讀", rejected: "已拒絕",
  creator: "Chamber 創作者", singleBackupTitle: "正在查看單篇備份", singleBackupBody: "其他文章仍保留在完整 Echo 時光牆中", backTimeline: "返回完整時光牆", privateTimeline: "🔐 私密回音牆", privateTimelineBody: "登入後會自動解鎖；若未完成可手動重試 {count} 篇", unlockingProgress: "自動解鎖中 {progress}", unlockAgain: "重新解鎖", filteringTag: "🏷️ 正在過濾標籤:", clearFilter: "清除過濾", loadingPosts: "正在從 Arweave 載入過濾貼文...", noPosts: "查無符合此平台或標籤條件的貼文。",
  fromPlatform: "來自 {platform}", viewSource: "🔗 檢視原文", decrypted: "已解密", privatePost: "私密加密文章", ownerAutoUnlock: "正在使用你的 Chamber 身分自動解鎖", approvedOnly: "只有作者核准的 Chamber 身分可以閱讀", autoUnlocking: "🔑 自動解鎖中...", sending: "送出中...", requestAuthor: "向作者申請閱讀", grantedRetry: "已獲准？重新解鎖", legacyMustRebackup: "舊版文章需由作者重新備份後才能分享",
  decryptingAlbum: "正在解密相簿圖片 {done}/{total}", imageFailures: " · {count} 張失敗", albumPartial: "相簿已部分解密：成功 {success}/{total} 張", videoSource: "🎬 影片來源 · {status}", videoComplete: "完整影片備份", videoPoster: "網址與封面備份", videoLinkOnly: "網址備份", noVideoUrl: "未提供影片來源網址", openVideo: "開啟影片", videoPosterLabel: "影片封面", albumCount: "相簿 · {count} 張", media: "媒體", incompleteMedia: "未完整取得", album: "相簿", backupMedia: "備份媒體", openAlbum: "開啟相簿瀏覽器",
  albumViewer: "相簿瀏覽器", openImage: "另開圖片", closeEsc: "Esc 關閉", previousImage: "上一張", nextImage: "下一張", thumbnailAlt: "縮圖 {index}",
} as const;

type FeedKey = keyof typeof zhTW;
const en: Record<FeedKey, string> = {
  extensionMissing: "Chamber Extension was not detected", sharingKeyMissing: "Chamber Extension has not created a sharing key",
  systemPasskeyTimeout: "The system passkey operation was canceled or timed out", extensionNoResponse: "Chamber Extension did not respond. Confirm it is installed and reload the page.", recoveryFailed: "Extension recovery operation failed",
  passwordManagerTimeout: "The password manager did not complete the passkey operation within 60 seconds. If its window is blank, use Windows Hello / Chrome instead.", // pragma: allowlist secret
  recoveryPendingC: "Passkey and Vault B are ready. Save C below, then confirm setup.", recoveryComplete: "✅ Recovery setup is complete. The selected provider keeps the passkey private key; Chamber never receives it. Offline recovery code C will not be shown again.",
  recoveryStatusFailed: "Could not read recovery status: {error}", creatingShares: "Asking the Extension to create recovery shares A, B, and C...", passkeySetupFailed: "Could not prepare passkey setup",
  waitingSystemPasskey: "Confirm the system passkey in Windows Hello or Chrome (up to 60 seconds)...", waitingManagerPasskey: "Confirm the passkey in your password manager (up to 60 seconds)...", passkeyVerifyFailed: "Passkey verification failed",
  setupSaveC: "✅ A remains in the Extension and B is in Recovery Vault. Save C somewhere else, then confirm.", setupFailed: "Setup failed: {error}", setupConfirmed: "✅ 2-of-3 key recovery is configured. A is in the Extension, B is in Vault, and you keep C offline.", confirmFailed: "Confirmation failed: {error}",
  rotateConfirm: "This creates a new A/B/C recovery set and replaces the old Vault B. The old C will no longer restore with Vault. Continue?", rotateChecking: "Authenticating the existing passkey before rotating recovery shares...", rotateUnavailable: "There is no complete recovery setup to rotate", passkeyReadFailed: "Could not read passkey settings", vaultRotateFailed: "Could not rotate Vault share B", rotateSaveC: "✅ Vault B was rotated. Save the new C below immediately and confirm; the old C is invalid.", rotateFailed: "Rotation failed: {error}",
  repairChecking: "Checking local A with Passkey Vault B...", repairUnavailable: "Local A is unavailable or Recovery Vault is not linked", repairSuccess: "✅ Key repair completed with local A and Passkey Vault B.", repairFailed: "A+B repair failed: {error}", pasteC: "Paste emergency recovery code C first.", checkingLocalC: "Checking whether local A can restore directly with C...", localCSuccess: "✅ Restored with local A plus emergency recovery code C; Vault was not needed.", invalidC: "Emergency recovery code C has an invalid format", incompleteC: "Emergency recovery code C is incomplete", authenticateForB: "Authenticate the original passkey to retrieve Vault share B...", restoreSuccess: "✅ Keys were restored and rotated. Save the new C below; the old C is invalid.", restoreFailed: "Restore failed: {error}",
  connectingMetaMask: "Connecting MetaMask...", walletConnected: "Wallet connected.", connectFailed: "Connection failed: {error}", startingSandbox: "Starting secure sandbox wallet...", sandboxConnected: "Sandbox wallet connected.", disconnecting: "Wallet disconnected. Returning home...",
  decryptTimeout: "Chamber Extension decryption timed out", ownerDecryptFailed: "Owner decryption failed", legacyOwnerOnly: "This legacy private backup can only be decrypted by its owner. The author must create a new revision before sharing.", installExtension: "Install and connect Chamber Extension first.", noGrant: "The author has not granted access yet.", grantReadFailed: "Could not read the post grant.", mediaDownloadFailed: "Media download failed ({status})", partialMedia: "Post decrypted; {success}/{total} images succeeded and {failed} failed.", decryptFailed: "Decryption failed: {error}",
  decryptPostsPartial: "Decrypted {success} posts; text decryption failed for {failed}.", decryptAlbums: "Decrypted {posts} posts; {success}/{total} album images succeeded.", decryptAll: "Decrypted {count} backups on the current timeline.",
  grantTimeout: "Chamber Extension timed out while creating the grant", grantCreateFailed: "Could not create the reading grant", requestFailed: "Request failed", approvedUnlocking: "The author approved access. Unlocking again.", requestSent: "Reading request sent. Waiting for the author.", readingRequestFailed: "Reading request failed", postNotVisible: "Return to the Echo timeline containing this post before approving it.", legacyReshare: "This is a legacy post. Back it up again from Facebook before sharing.", requestUpdateFailed: "Could not update the reading request", accessApproved: "Access to this post was approved. The recipient does not receive your recovery key.", accessRejected: "Reading request rejected.", requestHandleFailed: "Could not process the reading request",
  allFeed: "✨ All", chamberDisconnected: "Chamber disconnected", readingRequests: "🔔 Reading requests", guide: "User guide",
  externalWallet: "External wallet {wallet} (does not determine post ownership)", keyRecoverySettings: "🛡️ Key recovery", identityCopied: "Chamber identity address copied.", copyWallet: "📋 Copy wallet address", disconnectExternalWallet: "👋 Disconnect external wallet",
  recoveryTitle: "2-of-3 key recovery", recoveryIntro: "A remains in Chamber Extension on this Chrome profile; B is encrypted in Recovery Vault; you keep C offline. Any two shares can restore access. Echo only provides the interface and never stores the complete key.",
  recoveryReadyTitle: "Recovery setup complete", recoveryReadyBody: "Extension A and passkey-protected Vault B are ready. Keep the C you received earlier safe. C is neither stored nor shown again here.", rotateCSummary: "Lost C or suspect exposure? Create a new C", rotateProviderLabel: "Passkey provider for rotation", passwordManager: "🔐 Password manager", systemPasskey: "🖥️ System passkey", rotateWarning: "Your existing passkey must be verified. A, Vault B, and C will rotate; the old C becomes invalid immediately.", rotateCButton: "Create a new C and invalidate the old C",
  recoverySetupTitle: "Set up recovery and create C", recoverySetupBody: "Bitwarden, Google Password Manager, or the system secure area keeps the passkey private key. Chamber never receives or displays it. When complete, the Extension keeps A, Vault keeps B, and C is shown once for offline storage.", passkeyProviderLabel: "Passkey provider", passwordManagerExamples: "Bitwarden / 1Password, etc.", systemPasskeyExamples: "Windows Hello / Chrome", providerHint: "Use the same provider for setup and future recovery. If a password-manager window is blank, use the system passkey.", processing: "Processing...", saveCFirst: "Save recovery code C below first", setupRecoveryButton: "Set up recovery and create C", // pragma: allowlist secret
  restoreToolSummary: "Lost the Extension or changed devices? Open restore tools", restoreToolBody: "Use this only after recovery was configured and while you still have C. On this device, A+C can restore directly. If the Extension is lost, authenticate the original passkey to retrieve B, then restore with B+C.", restoreProviderLabel: "Passkey provider for restore", pasteSavedC: "Paste the emergency recovery code C you saved", restoreBC: "Restore with B+C and create a new recovery set", repairAB: "Local A is available: repair with Passkey Vault B",
  emergencyCTitle: "Emergency recovery code C", emergencyCBody: "Save it in a password manager, secure phone storage, or on paper. Do not keep the only copy on this computer.", cCopied: "Recovery code C copied. Paste it into another secure location, then confirm.", copyC: "📋 Copy C", cSavedElsewhere: "I saved C somewhere else",
  identityUnavailableTitle: "This Chrome profile's Chamber identity was not detected", identityUnavailableBody: "Your on-chain backups still exist. Make sure the Extension is enabled, then reload this page to unlock them. A MetaMask address does not identify the post owner.", wrongIdentity: "You are signed in as {identity}, which is not the Chamber identity for this Echo timeline, so private posts will not unlock automatically.",
  requestsTitle: "Reading requests", requestsBody: "Approval happens in Echo, while post keys are handled only by the local Chamber Extension.", noRequests: "There are no reading requests.", requestPost: "Post {post} · {date}", approvePost: "Allow this post", reject: "Reject", approvedSingle: "✅ Single-post access allowed", rejected: "Rejected",
  creator: "Chamber Creator", singleBackupTitle: "Viewing one backup", singleBackupBody: "Other posts remain available on the complete Echo timeline", backTimeline: "Back to full timeline", privateTimeline: "🔐 Private Echo timeline", privateTimelineBody: "Posts unlock automatically after sign-in. Retry {count} remaining posts if needed.", unlockingProgress: "Unlocking {progress}", unlockAgain: "Unlock again", filteringTag: "🏷️ Filtering tag:", clearFilter: "Clear filter", loadingPosts: "Loading filtered posts from Arweave...", noPosts: "No posts match this platform or tag filter.",
  fromPlatform: "From {platform}", viewSource: "🔗 View source", decrypted: "Decrypted", privatePost: "Private encrypted post", ownerAutoUnlock: "Unlocking with your Chamber identity", approvedOnly: "Only Chamber identities approved by the author can read this post", autoUnlocking: "🔑 Unlocking...", sending: "Sending...", requestAuthor: "Request access from author", grantedRetry: "Already approved? Unlock again", legacyMustRebackup: "The author must back up this legacy post again before it can be shared",
  decryptingAlbum: "Decrypting album images {done}/{total}", imageFailures: " · {count} failed", albumPartial: "Album partially decrypted: {success}/{total} images succeeded", videoSource: "🎬 Video source · {status}", videoComplete: "Complete video backup", videoPoster: "Link and poster backup", videoLinkOnly: "Link-only backup", noVideoUrl: "No video source URL is available", openVideo: "Open video", videoPosterLabel: "Video poster", albumCount: "Album · {count} images", media: "Media", incompleteMedia: "Incomplete", album: "Album", backupMedia: "Backed-up media", openAlbum: "Open album viewer",
  albumViewer: "Album viewer", openImage: "Open image", closeEsc: "Close (Esc)", previousImage: "Previous image", nextImage: "Next image", thumbnailAlt: "Thumbnail {index}",
};

export function feedTranslate(locale: Locale, key: FeedKey, variables: Record<string, string | number> = {}) {
  return (locale === "en" ? en[key] : zhTW[key]).replace(/\{(\w+)\}/g, (match, name) => Object.prototype.hasOwnProperty.call(variables, name) ? String(variables[name]) : match);
}
